class FlipwitchRegion:
    menu = "Menu"
    witch_woods = "Witchy Woods Upper"
    witch_woods_lower = "Witchy Woods Lower"
    spirit_town = "Spirit Town"
    cabaret_cafe = "Cabaret Cafe"
    pig_mansion = "Pig Mansion"
    shady_sewers = "Shady Sewers"
    early_ghost = "Early Ghost Castle"
    ghost_castle = "Ghost Castle"
    ghost_rose = "Ghost Castle Rose Garden"
    upper_ghost = "Upper Ghost Castle"
    jigoku = "Jigoku"
    club_demon = "Club Demon"
    fungal_forest = "Fungal Forest"
    tengoku = "Tengoku"
    tengoku_upper = "Tengoku Upper"
    angelic_hallway = "Angelic Hallway"
    angelic_upper = "Angelic Hallway Upper"
    deep_fungal = "Deep Fungal Forest"
    slime_citadel = "Slime Citadel"
    umi_umi = "Umi Umi"
    umi_umi_depths = "Umi Umi Depths"
    outside_chaos = "Outside Chaos Castle"
    chaos_castle = "Chaos Castle"



class FlipwitchEntrance:
    menu_to_woods = "Menu to Witchy Woods Upper"
    woods_to_woods_lower = "Witchy Woods to Witchy Woods Lower"
    witchy_to_spirit = "Witchy Woods Upper to Spirit Town"
    spirit_to_cafe = "Spirit Town to Cabaret Cafe"
    spirit_to_mansion = "Spirit Town to Pig Mansion"
    spirit_to_shady = "Spirit Town to Shady Sewers"
    spirit_to_early_ghost = "Spirit Town to Early Ghost Castle"
    early_ghost_to_ghost = "Early Ghost Castle to Ghost Castle"
    ghost_to_ghost_rose = "Ghost Castle to Ghost Castle Rose Garden"
    ghost_rose_to_upper_ghost = "Ghost Castle Rose Garden to Upper Ghost Castle"
    spirit_to_jigoku = "Spirit Town to Jigoku"
    jigoku_to_club_demon = "Jigoku to Club Demon"
    early_ghost_to_fungal_forest = "Early Ghost Castle to Fungal Forest"
    fungal_forest_to_tengoku = "Fungal Forest to Tengoku"
    tengoku_to_tengoku_upper = "Tengoku to Tengoku Upper"
    tengoku_upper_to_angelic_hallway = "Tengoku Upper to Angelic Hallway"
    angelic_to_angelic_upper = "Angelic Hallway to Angelic Hallway Upper"
    fungal_to_deep_fungal = "Fungal Forest to Deep Fungal Forest"
    deep_fungal_to_slime_citadel = "Deep Fungal Forest to Slime Citadel"
    fungal_to_umi_umi = "Fungal Forest to Umi Umi"
    umi_umi_to_umi_umi_depths = "Umi Umi to Umi Umi Depths"
    spirit_to_outside_chaos_castle = "Spirit Town to Outside Chaos Castle"
    outside_chaos_to_chaos = "Outside Chaos Castle to Chaos Castle"
