from worlds.lunacid.strings.regions_entrances import Region, Entrance
from .RegionClasses import RegionData, ConnectionData

lunacid_regions = [
    RegionData(Region.menu, [Entrance.menu_to_basin]),
    RegionData(Region.hollow_basin, [Entrance.to_wings_rest, Entrance.basin_to_archives, Entrance.basin_to_surface, Entrance.basin_to_temple]),
    RegionData(Region.temple_of_silence, [Entrance.temple_to_mire, Entrance.temple_to_forest]),
    RegionData(Region.wings_rest, [Entrance.wings_to_surface, Entrance.sheryl]),
    RegionData(Region.fetid_mire, [Entrance.mire_to_sea]),
    RegionData(Region.forbidden_archives, [Entrance.archives_to_chasm]),
    RegionData(Region.laetus_chasm, [Entrance.chasm_to_surface]),
    RegionData(Region.great_well_surface),
    RegionData(Region.yosei_forest, [Entrance.yosei_to_yosei_lower, Entrance.yosei_to_canopy]),
    RegionData(Region.forest_canopy),
    RegionData(Region.yosei_lower, [Entrance.yosei_lower_to_tomb]),
    RegionData(Region.sanguine_sea, [Entrance.sea_to_castle, Entrance.sea_to_tomb]),
    RegionData(Region.accursed_tomb, [Entrance.tomb_to_mausoleum]),
    RegionData(Region.mausoleum),
    RegionData(Region.castle_le_fanu, [Entrance.castle_to_red, Entrance.castle_to_white, Entrance.castle_to_battleground]),
    RegionData(Region.castle_le_fanu_red),
    RegionData(Region.holy_battleground),
    RegionData(Region.castle_le_fanu_white, [Entrance.white_to_blue, Entrance.white_to_throne]),
    RegionData(Region.castle_le_fanu_blue, [Entrance.castle_to_grotto, Entrance.castle_to_ballroom]),
    RegionData(Region.sealed_ballroom),
    RegionData(Region.boiling_grotto, [Entrance.grotto_to_tower, Entrance.grotto_to_sand]),
    RegionData(Region.tower_abyss),
    RegionData(Region.sand_temple),
    RegionData(Region.throne_chamber, [Entrance.throne_to_prison]),
    RegionData(Region.terminus_prison, [Entrance.prison_to_prison_dark]),
    RegionData(Region.terminus_prison_dark, [Entrance.prison_to_ash, Entrance.prison_to_arena]),
    RegionData(Region.labyrinth_of_ash),
    RegionData(Region.forlorn_arena, [Entrance.arena_to_fate]),
    RegionData(Region.chamber_of_fate, [Entrance.fate_to_sleeper]),
    RegionData(Region.grave_of_the_sleeper),
]

lunacid_entrances = [
    ConnectionData(Entrance.menu_to_basin, Region.hollow_basin),
    ConnectionData(Entrance.to_wings_rest, Region.wings_rest),
    ConnectionData(Entrance.sheryl, Region.sheryl_the_crow),
    ConnectionData(Entrance.basin_to_archives, Region.forbidden_archives),
    ConnectionData(Entrance.basin_to_surface, Region.great_well_surface),
    ConnectionData(Entrance.basin_to_temple, Region.temple_of_silence),
    ConnectionData(Entrance.temple_to_mire, Region.fetid_mire),
    ConnectionData(Entrance.temple_to_forest, Region.yosei_forest),
    ConnectionData(Entrance.wings_to_surface, Region.great_well_surface),
    ConnectionData(Entrance.mire_to_sea, Region.sanguine_sea),
    ConnectionData(Entrance.archives_to_chasm, Region.laetus_chasm),
    ConnectionData(Entrance.chasm_to_surface, Region.great_well_surface),
    ConnectionData(Entrance.yosei_to_canopy, Region.forest_canopy),
    ConnectionData(Entrance.yosei_to_yosei_lower, Region.yosei_lower),
    ConnectionData(Entrance.yosei_lower_to_tomb, Region.accursed_tomb),
    ConnectionData(Entrance.sea_to_castle, Region.castle_le_fanu),
    ConnectionData(Entrance.sea_to_tomb, Region.accursed_tomb),
    ConnectionData(Entrance.tomb_to_mausoleum, Region.mausoleum),
    ConnectionData(Entrance.castle_to_red, Region.castle_le_fanu_red),
    ConnectionData(Entrance.castle_to_white, Region.castle_le_fanu_white),
    ConnectionData(Entrance.castle_to_battleground, Region.holy_battleground),
    ConnectionData(Entrance.white_to_throne, Region.throne_chamber),
    ConnectionData(Entrance.white_to_blue, Region.castle_le_fanu_blue),
    ConnectionData(Entrance.castle_to_ballroom, Region.sealed_ballroom),
    ConnectionData(Entrance.castle_to_grotto, Region.boiling_grotto),
    ConnectionData(Entrance.grotto_to_tower, Region.tower_abyss),
    ConnectionData(Entrance.throne_to_prison, Region.terminus_prison),
    ConnectionData(Entrance.prison_to_arena, Region.forlorn_arena),
    ConnectionData(Entrance.prison_to_ash, Region.labyrinth_of_ash),
    ConnectionData(Entrance.arena_to_fate, Region.chamber_of_fate),
    ConnectionData(Entrance.fate_to_sleeper, Region.grave_of_the_sleeper),
    ConnectionData(Entrance.grotto_to_sand, Region.sand_temple),
    ConnectionData(Entrance.prison_to_prison_dark, Region.terminus_prison_dark)


]
