class Enemy:
    snail = "Snail"
    milk_snail = "Milk Snail"
    mummy = "Mummy"
    mummy_knight = "Mummy Knight"
    shulker = "Shulker"
    ankou = "Ankou"
    spectre = "Spectre"

    slime = "Slime"
    slime_skeleton = "Slime Skeleton"
    skeleton = "Skeleton"
    rat = "Rat"
    rat_king = "Rat King"
    rat_queen = "Rat Queen"
    mimic = "Mimic"
    devil_slime = "Devil Slime"

    yakul = "Yakul"
    kodama = "Kodama"
    lunaga = "Lunaga"
    ga_mangetsu = "Ga-Mangetsu"
    venus = "Venus"
    neptune = "Neptune"
    unilateralis = "Unilateralis"
    tillandsia = "Tillandsia"

    enlightened_one = "Enlightened One"
    necronomicon = "Necronomicon"
    chimera = "Chimera"

    hemalith = "Hemalith"

    mare = "Mare"
    mi_go = "Mi-Go"
    phantom = "Phantom"
    cursed_painting = "Cursed Painting"

    poltergeist = "Poltergeist"
    vampire = "Vampire"
    vampire_page = "Vampire Page"
    giant_bat = "Giant Bat"
    malformed = "Malformed"

    malformed_horse = "Malformed Horse"
    hallowed_husk = "Hallowed Husk"

    ikurrilb = "Ikurr'ilb"
    obsidian_skeleton = "Obsidian Skeleton"
    serpent = "Serpent"
    anpu = "Anpu"
    embalmed = "Embalmed"

    lunam = "Cerritulus Lunam"
    jailor = "Jailor"
    lupine_skeleton = "Lupine Skeleton"
    giant_skeleton = "Giant Skeleton"
    infested_corpse = "Infested Corpse"

    sucsarian = "Sucsarian"
    ceres = "Ceres"
    vesta = "Vesta"
    gloom_wood = "Gloom Wood"

    centaur = "Centaur"
    cetea = "Cetea"
