class GenericItem:
    health_vial = "Health Vial"
    mana_vial = "Mana Vial"
    antidote = "Antidote"
    blood_wine = "Blood Wine"
    crystal_shard = "Crystal Shard"
    ocean_elixir = "Ocean Elixir"
    earth_elixir = "Earth Elixir"
    poison_throwing_knife = "Poison Throwing Knife"
    black_book = "Black Book"
    holy_water = "Holy Water"
    fairy_moss = "Fairy Moss"
    light_urn = "Light Urn"
    ashes = "Ashes"
    cloth_bandage = "Cloth Bandage"
    moonlight_vial = "Moonlight Vial"
    spectral_candle = "Spectral Candle"
    dark_urn = "Dark Urn"
    wisp_heart = "Wisp Heart"
    staff_of_osiris = "Staff of Osiris"
    enchanted_key = "Enchanted Key"


class UniqueItem:
    white_tape = "White VHS Tape"
    vhs_tape = "VHS Tape"
    corrupted_key = "Corrupted Key"
    skull_of_josiah = "Skull of Josiah"
    vampiric_symbol_w = "Vampiric Symbol (W)"
    vampiric_symbol_a = "Vampiric Symbol (A)"
    vampiric_symbol_e = "Vampiric Symbol (E)"
    crystal_lantern = "Crystal Lantern"
    terminus_prison_key = "Terminus Prison Key"
