class BaseLocation:
    wings_rest_crystal_shard = "WR: Bench"
    wings_rest_ocean_elixir = "WR: Rafters"
    wings_rest_clives_gift = "WR: Clive's Gift"
    wings_rest_demi_gift = "WR: Demi's Introduction Gift"
    wings_rest_demi_orb = "WR: Demi's Victory Gift"

    hollow_basin_starting_sword = "HB: Starting Weapon"
    hollow_basin_right_water_right = "HB: Rightmost Water Room (Right)"
    hollow_basin_right_water_left = "HB: Rightmost Water Room (Left)"
    hollow_basin_left_water = "HB: Leftmost Water Room"
    hollow_basin_demi_chest = "HB: Chest Near Demi"
    hollow_basin_enchanted_door = "HB: Near Enchanted Door"
    hollow_basin_dark_item = "HB: Dark Tunnel After Enchanted Door"

    temple_fountain = "HB: Temple Fountain"
    temple_ritual_table = "HB: Temple Ritual Table"
    temple_altar_chest = "HB: Temple Altar Chest"
    temple_pillar_left = "HB: Temple Hidden Room Behind Pillar (Left)"
    temple_pillar_right = "HB: Temple Hidden Room Behind Pillar (Right)"
    temple_ritual_ring = "HB: Temple Ritual Table After Bridge"
    temple_small_pillar = "HB: Temple Small Pillar Top"
    temple_pillar_room_left = "HB: Temple Pillar Room Left"
    temple_pillar_room_back_left = "HB: Temple Pillar Room Back Left"
    temple_pillar_room_back_right = "HB: Temple Pillar Room Back Right"
    temple_pillar_room_hidden_room = "HB: Temple Pillar Room Hidden Room"
    temple_hidden_room_in_sewer = "HB: Temple Hidden Room In Sewer"
    temple_table_in_sewer = "HB: Temple Table in Sewer"
    temple_sewer_puzzle = "HB: Temple Sewer Puzzle"
    temple_blood_altar = "HB: Temple Blood Altar"
    temple_path_to_forest = "HB: Alcove on Path to Yosei Forest"

    mire_room_left_foyer = "FM: Room Left of Foyer"
    mire_hidden_slime_chest = "FM: Hidden Slimey Chest Near Entrance"
    mire_upper_overlook_left = "FM: Hidden Upper Overlook (Left)"
    mire_upper_overlook_right = "FM: Hidden Upper Overlook (Right)"
    mire_bonerard_trash = "FM: Bonerard's Trash"
    mire_rubble_bridge = "FM: Rubble Near Overlook Bridge"
    mire_skeleton_chest = "FM: Slime Skeleton Chest"
    mire_jellisha_trash = "FM: Jellisha's Trash"
    mire_jellisha_reward = "FM: Jellisha's Quest Reward"
    mire_hidden_chest_near_underworks = "FM: Hidden Chest Near Underworks"
    mire_rubble_near_illusory_wall = "FM: Rubble Near Illusory Wall"
    mire_underwater_pipe = "FM: Underwater Pipe"
    mire_underworks_waterfall = "FM: Underworks Waterfall"
    mire_underworks_skeleton = "FM: Underworks Skeleton"
    mire_path_to_sea_left = "FM: Path to Sanguine Sea (Left)"
    mire_path_to_sea_right = "FM: Path to Sanguine Sea (Right)"

    sea_pillar = "SS: Pillar In Front of Castle Le Fanu"
    sea_underblood = "SS: Underblood Near Castle Le Fanu"
    sea_blood_island = "SS: Blood Island"
    sea_kill_jotunn = "SS: Killing the Jotunn"

    catacombs_coffin_stairs = "AT: Catacombs Coffins Near Stairs"
    catacombs_coffin_blue_light = "AT: Catacombs Coffins With Blue Light"
    corrupted_room = "AT: Corrupted Room"
    catacombs_coffin_gate = "AT: Gated Tomb Near Corrupted Room"
    catacombs_hidden_room = "AT: Catacombs Hidden Room"
    catacombs_deep_coffin_storage = "AT: Deep Coffin Storage"
    catacombs_restore_vampire = "AT: Red Skeleton"

    mausoleum_hidden_chest = "AT: Mausoleum Hidden Chest"
    mausoleum_upper_table = "AT: Mausoleum Upper Alcove Table"
    mausoleum_maze_intro = "AT: Mausoleum Maze (Early)"
    mausoleum_maze_mid = "AT: Mausoleum Maze (Middle)"
    mausoleum_center_right = "AT: Mausoleum Central Room (Right)"
    mausoleum_center_left = "AT: Mausoleum Central Room (Left)"
    mausoleum_center_back = "AT: Mausoleum Central Room (Back)"
    mausoleum_center_left_path = "AT: Mausoleum Central Room (Left Path)"
    mausoleum_center_right_path = "AT: Mausoleum Central Room (Right Path)"
    mausoleum_kill_death = "AT: Kill Death"

    tomb_tomb_with_switch = "AT: Tomb With Switch"
    tomb_tomb_with_corpse = "AT: Tomb With Sitting Corpse"
    tomb_demi_chest = "AT: Demi Chest"
    tomb_near_light_switch = "AT: Near Light Switch"
    tomb_hidden_room = "AT: Hidden Room in Tomb"
    tomb_hidden_chest = "AT: Hidden Chest in Tomb"

    yosei_barrels = "YF: Barrel Group"
    yosei_blood_pool = "YF: Blood Pool"
    yosei_branch_in_tree = "YF: Banches Within Tree"
    yosei_chest_near_tree = "YF: Chest Near Tree"
    yosei_blood_plant_insides = "YF: Blood Plant's Insides"
    yosei_hanging_in_trees = "YF: Hanging In The Trees"
    yosei_hidden_chest = "YF: Hidden Chest"
    yosei_room_defended_by_blood_plant = "YF: Room Defended by Blood Plant"
    yosei_patchouli_key = "YF: Patchouli's Canopy Offer"
    yosei_patchouli_quest = "YF: Patchouli's Reward"

    canopy_branch_edge = "FC: Branch Lower Edge"
    branch_cave = "FC: Branch Cave"
    canopy_chest = "FC: Chest"
    canopy_wooden_statue = "FC: Wooden Statue (Josiah)"
    canopy_wooden_sitting = "FC: Wooden Statue (Sitting)"

    archives_back_room_past_bridge = "FbA: Back Room Past Bridge"
    archives_strange_corpse = "FbA: Strange Corpse"
    archives_short_wall_near_trees = "FbA: Short Wall Near Trees"
    archives_against_wall_near_trees = "FbA: Against Wall Near Trees"
    archives_snail_lectern_near = "FbA: Snail Lectern (Near)"
    archives_snail_lectern_far = "FbA: Snail Lectern (Far)"
    archives_rug_on_balcony = "FbA: Rug on Balcony"
    archives_rooftop = "FbA: Rooftops"
    archives_hidden_room_upper = "FbA: Hidden Room Upper Floor"
    archives_hidden_room_lower = "FbA: Hidden Room Lower Floor"
    archives_near_twisty_tree = "FbA: Near Twisty Tree"
    archives_uwu = "FbA: uwu"
    archives_daedalus_one = "FbA: Daedalus Knowledge (First)"
    archives_daedalus_two = "FbA: Daedalus Knowledge (Second)"
    archives_daedalus_third = "FbA: Daedalus Knowledge (Third)"
    archives_corner_near_daedalus = "FbA: Corner Near Daedalus"

    castle_outside_corner = "CLF: Outside Corner"
    castle_cell_south = "CLF: Cattle Cell (South)"
    castle_cell_west = "CLF: Cattle Cell (West)"
    castle_cell_center = "CLF: Cattle Cell (Center)"
    castle_cell_north = "CLF: Cattle Cell (North)"
    castle_hidden_cell = "CLF: Hidden Cattle Cell"

    castle_hallway_rubble_room = "CLF: Hallway Rubble Room"
    castle_hallway_dining_room = "CLF: Hallway Dining Room"
    castle_garrat_resting_room_left = "CLF: Garrat Resting Room (Fountain)"
    castle_garrat_resting_room_back = "CLF: Garrat Resting Room (Wall)"
    castle_hallway_deadend_before_door = "CLF: Hallway Dead End Before Blue Doors"
    castle_upper_floor_coffin_small = "CLF: Upper Floor Coffin Room (Small Room)"
    castle_upper_floor_coffin_large = "CLF: Upper Floor Coffin Room (Large Room)"
    castle_upper_floor_coffin_double = "CLF: Upper Floor Coffin Room (Double)"
    castle_upper_floor_coffin_hallway = "CLF:  Upper Floor Coffin Room (Halllway)"

    ballroom_small_room_lounge = "SB: Entry Small Room Lounge"
    ballroom_entry_hidden_couch_top = "SB: Entry Hidden Couch Top"
    ballroom_entry_hidden_couch_bottom = "SB: Entry Hidden Couch Bottom"
    ballroom_entry_hidden_cave_in_lounge = "SB: Entry Hidden Cave in a Lounge"
    ballroom_entry_long_table = "SB: Entry Lounge Long Table"
    ballroom_side_hidden_cave = "SB: Side Hidden Cave"
    ballroom_side_chest_near_switch = "SB: Side Chest Near Switch"
    ballroom_side_painting = "SB: Side Painting Viewing Room"
    ballroom_side_hidden_casket_room = "SB: Side Hidden Casket Room"
    ballroom_side_xp_drain = "SB: Side XP Drain Party Room"

    chasm_hidden_chest = "LC: Hidden Room"
    chasm_invisible_cliffside = "LC: Invisible Path to Cliffside"

    surface_demi_gift = "GWS: Demi's Gift"

    throne_book = "TC: Crilall's Book Repository"

    battlefield_book = "AHB: Sngula Umbra's Remains"

    grotto_slab_of_bridge = "BG: Slab of a Broken Bridge"
    grotto_hidden_chest = "BG: Hidden Chest"
    grotto_corpse_beneath_entrance = "BG: Corpse Beneath Entrance"
    grotto_triple_secret_chest = "BG: Triple Hidden Chest"
    grotto_rocks_near_lava_switch = "BG: Lava Overseeing Dragon Switch"
    grotto_through_switch_tunnel = "BG: Through Dragon Switch Tunnel"

    sand_room_buried_in_sand = "ST: Room Buried in Sand"
    sand_top_right_sarcophagus = "ST: Top Right Sarcophagus"
    sand_second_floor_snake = "ST: Second Floor Snake Room"
    sand_basement_snake_pit = "ST: Basement Snake Pit"
    sand_hidden_sarcophagus = "ST: Hidden Sarcophagus"
    sand_second_floor_dead_end = "ST: Second Floor Dead End"
    sand_lunacid_sandwich = "ST: Lunacid Sandwich"
    sand_chest_near_switch = "ST: Chest Near Switch"
    sand_chest_overlooking_crypt = "ST: Chest Overlooking Crypt"
    sand_switch_maze = "ST: Floor Switch Maze"
    sand_basement_rubble = "ST: Basement Stone Rubble"
    sand_triple_sarcophagus = "ST: Triple Sarcophagus"

    abyss_floor_5 = "TA: Floor 5 Chest"
    abyss_floor_10 = "TA: Floor 10 Chest"
    abyss_floor_15 = "TA: Floor 15 Chest"
    abyss_floor_20 = "TA: Floor 20 Chest"
    abyss_floor_25 = "TA: Floor 25 Chest"
    abyss_floor_30 = "TA: Floor 30 Chest"
    abyss_floor_35 = "TA: Floor 35 Chest"
    abyss_floor_40 = "TA: Floor 40 Chest"
    abyss_floor_45 = "TA: Floor 45 Chest"
    abyss_floor_50 = "TA: Floor 50 Chest"
    abyss_prize = "TA: Prize Beneath Tree"

    prison_f3_locked_left = "TP: Third Floor Locked Cell Left"
    prison_f3_locked_right = "TP: Third Floor Locked Cell Right"
    prison_f3_locked_south = "TP: Third Floor Locked Cell South"
    prison_f3_bottomless_pit = "TP: Almost Bottomless Pit"
    prison_f2_broken_cell = "TP: Second Floor Broken Cell"
    prison_f2_jailer_table = "TP: Second Floor Jailer's Table"
    prison_f1_hidden_cell = "TP: First Floor Hidden Cell"
    prison_f1_hidden_debris_room = "TP: First Floor Hidden Debris Room"
    prison_f1_remains = "TP: First Floor Remains"
    prison_b2_near_elevator = "TP: Second Basement Near Elevator"
    prison_b2_guarded_corner_one = "TP: Second Basement Guarded Alcove (Left)"
    prison_b2_guarded_corner_two = "TP: Second Basement Guarded Alcove (Right)"
    prison_b2_deep_alcove = "TP: Second Basement Long Alcove"
    prison_b2_bone_pit = "TP: Second Basement Bone Pit"
    prison_b2_egg_resting_place = "TP: Egg's Resting Place"
    prison_f4_hanging = "TP: Fourth Floor Cell Hanging Remains"
    prison_f4_maledictus_secret = "TP: Fourth Floor Maledictus Secret"
    prison_f4_hidden_beds = "TP: Fourth Floor Hidden Jailer Sleeping Spot"
    prison_f4_jailer_break_room = "TP: Fourth Floor Jailer Break Room"
    prison_f4_monk_room_one = "TP: Etna's Resting Place Item 1"
    prison_f4_monk_room_two = "TP: Etna's Resting Place Item 2"
    prison_f4_monk_room_three = "TP: Etna's Resting Place Item 3"
    prison_f4_collapsed_tunnel = "TP: Fourth Floor Collapsed Tunnel"

    arena_broken_sword = "FlA: Corpse Waiting For A Full Moon"
    arena_rock_parkour = "FlA: Entry Rock Parkour"
    arena_earth_hidden_plant_haven = "FlA: Temple of Earth Hidden Plant Haven"
    arena_earth_hidden_room = "FlA: Temple of Earth Hidden Room"
    arena_earth_earthen_temple = "FlA: Temple of Earth Fractured Chest"
    arena_earth_chest_near_switch = "FlA: Temple of Earth Chest Near Switch"
    arena_water_room_near_water = "FlA: Temple of Water Room Near Water"
    arena_water_dead_end_near_water = "FlA: Temple of Water Corner Near Water"
    arena_water_collapsed_end_near_balcony = "FlA: Temple of Water Collapsed End Near Balcony"
    arena_water_hidden_basement_left = "FlA: Temple of Water Hidden Basement (Left)"
    arena_water_hidden_basement_right = "FlA: Temple of Water Hidden Basement (Right)"
    arena_water_hidden_laser_room = "FlA: Temple of Water Hidden Laser Room"
    arena_water_hidden_alcove_before = "FlA: Temple of Water Hidden Alcove Before Stairs"
    arena_water_hidden_alcove_left = "FlA: Temple of Water Hidden Alcove (Left)"
    arena_water_hidden_alcove_right = "FlA: Temple of Water Hidden Alcove (Right)"
    arena_water_hidden_alcove_before_switch = "FlA: Temple of Water Hidden Alcove Before Switch"
    arena_water_underwater_temple = "FlA: Temple of Water Fractured Chest"
    arena_water_chest_near_switch = "FlA: Temple of Water Chest Near Switch"

    ash_entry_coffin = "LA: Entry Coffin"
    ash_jotunn_remains = "LA: Jotunn Remains"
    ash_cetea_statue = "LA: Behind Statue"
    ash_rocks_near_switch = "LA: Rocks Near Switch"
    ash_forbidden_light_chest = "LA: Forbidden Light Chest"
    ash_hidden_chest = "LA: Hidden Light Chest"
    ash_path_maze = "LA: NNSNSSNSNN Lost Maze"

    fate_lucid_blade = "CF: Calamis' Weapon of Choice"


class ShopLocation:
    buy_enchanted_key = "Buy Enchanted Key"
    buy_rapier = "Buy Rapier"
    buy_steel_needle = "Buy Steel Needle"
    buy_crossbow = "Buy Crossbow"
    buy_oil_lantern = "Buy Oil Lantern"
    buy_ocean_elixir_sheryl = "Buy Ocean Elixir (Sheryl)"
    buy_ocean_elixir_patchouli = "Buy Ocean Elixir (Patchouli)"
    buy_privateer_musket = "Buy Privateer Musket"
    buy_jotunn_slayer = "Buy Jotunn Slayer"


class DropLocation:
    snail_drop = "Snail: Summon Snail Drop"
    mummy_drop = "Mummy: Rusted Sword Drop"
    milk_snail_drop = "Milk Snail: Ice Sickle Drop"
    skeleton_weapon_drop = "Skeleton: Skeleton Axe Drop"
    skeleton_spell_drop = "Skeleton: Dark Skull Drop"
    phantom_drop = "Phantom: Cursed Blade Drop"
    kodama_drop = "Kodama: Summon Kodama Drop"
    chimera_drop = "Chimera: Quick Stride Drop"
    vampire_drop = "Vampire Page: Lyrian Longsword Drop"
    horse_drop = "Malformed Horse: Brittle Arming Sword Drop"
    obsidian_skeleton_drop_1 = "Obsidian Skeleton: Obsidian Cursebrand Drop"
    obsidian_skeleton_drop_2 = "Obsidian Skeleton: Obsidian Poisonguard Drop"
    anpu_drop_1 = "Anpu: Golden Kopesh Drop"
    anpu_drop_2 = "Anpu: Golden Sickle Drop"
    jailor_drop = "Jailor: Jailor's Candle Drop"
    sucsarian_drop_1 = "Sucsarian: Sucsarian Dagger Drop"
    sucsarian_drop_2 = "Sucsarian: Sucsarian Spear Drop"
    cetea_drop = "Cetea: Tornado Drop"
    sea_demon = "Abyssal Demon: Ocean Elixir Drop"
