
class LunacidRegion:

    menu = "Menu"
    hollow_basin = "Hollow Basin"
    temple_of_silence = "Temple of Silence"
    wings_rest = "Wing's Rest"
    fetid_mire = "The Fetid Mire"
    yosei_forest = "Yosei Forest"
    forest_canopy = "Forest Canopy"
    accursed_tomb = "Accursed Tomb"
    castle_le_fanu = "Castle Le Fanu"
    castle_le_fanu_white = "Castle Le Fanu White Area"
    castle_le_fanu_blue = "Castle Le Fanu Blue Area"
    castle_le_fanu_red = "Castle Le Fanu Red Area"
    boiling_grotto = "Boiling Grotto"
    forbidden_archives = "Forbidden Archives"
    laetus_chasm = "Laetus Chasm"
    great_well_surface = "Great Well Surface"
    sanguine_sea = "The Sanguine Sea"
    sealed_ballroom = "Sealed Ballroom"
    throne_chamber = "Throne Chamber"
    holy_battleground = "A Holy Battleground"
    terminus_prison = "Terminus Prison"
    terminus_prison_dark = "Terminus Prison Dark Areas"
    tower_abyss = "Tower of Abyss"
    labyrinth_of_ash = "Labyrinth of Ash"
    forlorn_arena = "Forlorn Arena"
    chamber_of_fate = "Chamber of Fate"
    grave_of_the_sleeper = "Grave of the Sleeper"
    daedalus = "Daedalus"
    mausoleum = "Mausoleum"
    yosei_lower = "Yosei Forest Lower"
    sheryl_the_crow = "Sheryl the Crow"
    sand_temple = "Sand Temple"


class LunacidEntrance:
    menu_to_basin = "Menu to Hollow Basin"
    to_wings_rest = "To Wing's Rest"
    wings_to_surface = "Wing's Rest to Great Well Surface"
    basin_to_temple = "Hollow Basin to Temple of Silence"
    temple_to_mire = "Temple of Silence to The Fetid Mire"
    temple_to_forest = "Hollow Basin to Yosei Forest"
    basin_to_archives = "Hollow Basin to Forbidden Archives"
    basin_to_surface = "Hollow Basin to Great Well Surface"
    mire_to_sea = "The Fetid Mire to The Sanguine Sea"
    sea_to_tomb = "The Sanguine Sea to Accursed Tomb"
    tomb_to_mausoleum = "Accursed Tomb to Mausoleum"
    sea_to_castle = "The Sanguine Sea to Castle Le Fanu"
    yosei_to_yosei_lower = "Yosei Forest to Yosei Forest Lower"
    yosei_to_canopy = "Yosei Forest to Forest Canopy"
    yosei_lower_to_tomb = "Yosei Forest Lower to Accursed Tomb"
    archives_to_chasm = "Forbidden Archives to Laetus Chasm"
    archives_to_daedalus = "Forbidden Archives to Daedalus"
    chasm_to_surface = "Laetus Chasm to Great Well Surface"
    white_to_blue = "Castle Le Fanu White Area to Castle Le Fanu Blue Area"
    white_to_throne = "Castle Le Fanu White Area to Throne Chamber"
    castle_to_white = "Castle Le Fanu to Castle Le Fanu White Area"
    castle_to_red = "Castle Le Fanu to Castle Le Fanu Red Area"
    castle_to_ballroom = "Castle Le Fanu to Sealed Ballroom"
    castle_to_battleground = "Castle Le Fanu to A Holy Battleground"
    castle_to_grotto = "Castle Le Fanu to Boiling Grotto"
    throne_to_prison = "Throne Chamber to Terminus Prison"
    grotto_to_tower = "Boiling Grotto to Tower of Abyss"
    prison_to_ash = "Terminus Prison Dark Areas to Labyrinth of Ash"
    prison_to_arena = "Terminus Prison Dark Areas to Forlorn Arena"
    arena_to_fate = "Forlorn Arena to Chamber of Fate"
    fate_to_sleeper = "Chamber of Fate to Grave of the Sleeper"
    sheryl = "Wing's Rest to Sheryl the Crow"
    grotto_to_sand = "Boiling Grotto to Sand Temple"
    prison_to_prison_dark = "Terminus Prison to Terminus Prison Dark Areas"

