class Spell:
    barrier = "Barrier"
    bestial_communion = "Bestial Communion"
    blood_drain = "Blood Drain"
    blood_strike = "Blood Strike"
    blue_flame_arc = "Blue Flame Arc"
    coffin = "Coffin"
    corpse_transformation = "Corpse Transformation"
    earth_strike = "Earth Strike"
    earth_thorn = "Earth Thorn"
    fire_worm = "Fire Worm"
    flame_flare = "Flame Flare"
    flame_spear = "Flame Spear"
    ghost_light = "Ghost Light"
    holy_warmth = "Holy Warmth"
    icarian_flight = "Icarian Flight"
    ice_spear = "Ice Spear"
    ice_tear = "Ice Tear"
    ignis_calor = "Ignis Calor"
    lava_chasm = "Lava Chasm"
    light_reveal = "Light Reveal"
    lightning = "Lightning"
    lithomancy = "Lithomancy"
    moon_beam = "Moon Beam"
    poison_mist = "Poison Mist"
    rock_bridge = "Rock Bridge"
    slime_orb = "Slime Orb"
    spirit_warp = "Spirit Warp"
    summon_fairy = "Summon Fairy"
    summon_ice_sword = "Summon Ice Sword"
    wind_dash = "Wind Dash"
    wind_slicer = "Wind Slicer"


class MobSpell:
    summon_snail = "Summon Snail"
    summon_kodama = "Summon Kodama"
    tornado = "Tornado"
    dark_skull = "Dark Skull"
    quick_stride = "Quick Stride"
